@ECHO ON
IF EXIST C:\hda.mbr GOTO FAIL
IF NOT EXIST mbrbm.bin GOTO FAIL
COPY mbrbm.bin C:\
C:
CD \
DEL BOOT.MBR
FDISK /SMBR 1
IF NOT EXIST BOOT.MBR GOTO FAIL
COPY BOOT.MBR hda.mbr
IF NOT EXIST C:\hda.mbr GOTO FAIL
COPY mbrbm.bin BOOT.MBR
FDISK /AMBR 1
ECHO KEEP THE FILE C:\hda.mbr AS BACKUP OF ORIGINAL MBR
GOTO EXIT
:FAIL
ECHO mbrbm installation failed
:EXIT
